### PR TITLE
fix(README): markdown URLs should be enclose in `

### PR DESCRIPTION
**Pull request by realeinherjar**
Just a quick fix so I can run CI in #9.
https://github.com/rust-bitcoin/www.rust-bitcoin.org/pull/9#issuecomment-1734577512

Cc @tcharding

### CODE REVIEW

**Review by tcharding — APPROVED** [review]
~ACK 8d59097ec059d8e1b0983d425b26c0c0fdeecde0~

**Comment by tcharding** [comment]
Woops, recinding my ACK, this doesn't actually render correctly. https://github.com/realeinherjar/www.rust-bitcoin.org/tree/einherjar/quick-fix

**Comment by realeinherjar** [comment]
What about this?

**Review by tcharding — APPROVED** [review]
ACK cb0cfe42e525db8a47c7143a6555d10c7fa91cb1

**Pull request merged**
